### ISSUE TITLE
As a user, I would like to have reviewers automatically assigned based on load

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#101]
Many development teams struggle with the problem of reviews being distributed unevenly. This results in inefficient workloads and reduced collaboration.

It would be nice to have a tool that automatically assigns reviewers for pull requests based on the number of pull requests everyone has reviewed. This would need to be configurable by repo and take into account teams.

Note that GitHub [CODEOWNERS](https://help.github.com/articles/about-codeowners/) does something similar where reviewers are assigned based on what code was touched.

Specifically requested by @akshat12, @jisung [(+)](https://app.intercom.io/a/apps/gyuvmw0d/inbox/inbox/1949685/conversations/19728932682), @twymer, @cariwest

> One cool feature (for the future! Not necessarily now) could be the ability to randomly assign a code review. So, you could ask Pull Reminders to assign a developer to do your code review so that all code reviews are split evenly across all people on the team. One thing to consider for this, though, is that we sometimes review code in groups — like, front-end code should be reviewed by front-end engineers, or assigning all code reviews for a feature within the team that's working on the feature. So it's a pretty complex feature — it just seems like it might be a nice complement to the integration you're developing!

> A longer term feature request could be something to help distribute more evenly or just ways in the UI to help identify rolling patterns of things like that.

> Is it possible to assign automatically one PR reviewer randomly among the team members every PR has been created?

**Comment by jisung** [comment]
Our team is really looking forward to using this feature and some other teams in the company may start using this PullReminders after this feature is on. Thanks 👏

**Comment by abinoda** [comment]
@jisung In order to help us with the requirements for this, could you tell me more about how you'd want this to work for your organization? How do you want reviewers to be assigned and what options might you want to configure?

My assumption is that settings should be configured per repo and might include number of reviewers to assign, what groups (GitHub Team) of reviewers to pool from, and how reviews should be distributed amongst reviewers (ie. should every person review the same # of reviews? should some people ALWAYS be assigned as a reviewer?).

**Comment by jisung** [comment]
@abinoda 
Most of your assumption looks right. This is our current rules to assign a reviewer to PR, please let me know if anything unclear: 
1. Each repo has a pre-defined set of reviewers 
2. When PR is created, the reviewer should be assigned automatically from the members.
3. If a reviewer is not available at that time (ie. github status is busy), he or she should not be assigned to the PR.

**Comment by abinoda** [comment]
@jisung Couple questions:

> Each repo has a pre-defined set of reviewers

At your company, approx. how many repos do you have, and do they all have different pre-defined reviewers? Or do they fall into two or three different patterns?

> When PR is created, the reviewer should be assigned automatically from the members.

Just one reviewer? Or two?

**Comment by jisung** [comment]
@abinoda 
> how many repos do you have

Company has a lot of repos but the repos need for this automatic PR assignment are under 5 currently. 
> do they all have different pre-defined reviewers

Yeah but we manage this by [Team](https://help.github.com/articles/organizing-members-into-teams/). For example, if android-dev repo has two team (android-team, ios-team) and 5 collaborators, then reviewers will come from only android-team.
> Just one reviewer? Or two?

Just one is enough for now. (it would be great to support multiple reviewers optionally)

Thanks

**Comment by abinoda** [comment]
@jisung Perfect. This is very in line with what we're working on. And thanks for suggesting making use of GitHub's new status feature - we were thinking the same!

**Comment by abinoda** [comment]
@jisung @NejcZupec @alexmitc 

I have enabled Pull Assigner for your accounts. Please give it a try and report back any questions or feedback! I created a [setup guide](https://github.com/pullreminders/guides/wiki/Pull-Assigner) with some tips.

There are three potential future features we are considering:

1. Some way to deal with people who are OOO, although this doesn't seem like a huge issue since review assignment can always be manually changed
2. Adding a consent step where reviewers receive a Slack message asking them whether they accept the review request. If they do not, the bot will assign someone else.
3. Allowing you to set teams to be automatically requested based on repo, similar to [CODEOWNERS](https://help.github.com/articles/about-code-owners/) but more easily manageable through a UI.

If anyone else is watching this and interested in joining the private beta please let me know!

**Comment by abinoda** [comment]
![pullassigner](https://user-images.githubusercontent.com/50083/52589156-6a00f680-2dfb-11e9-80d8-dbd85a19a6b9.gif)

**Comment by abinoda** [comment]
![pullassigner](https://user-images.githubusercontent.com/50083/52589516-38d4f600-2dfc-11e9-8f85-723426f7fb14.gif)

**Comment by abinoda** [comment]
![pullassigner](https://user-images.githubusercontent.com/50083/52602954-d131a180-2e21-11e9-8b54-8e485c8944f6.gif)

**Comment by jisung** [comment]
@abinoda 
This is really good and works perfectly so far. Especially, the combination of CODEOWNERS and Pull-Assigner shows amazing usability. Well done, Thanks!

**Comment by abinoda** [comment]
Closing this – please submit feature requests as new issues!
