### ISSUE TITLE
As a user, I would like to receive DM's for GitHub Issue activity

### ISSUE THREAD

**Issue by Kivol** [pullreminders/backlog#104]
Hello,
This Pull Reminders app looks like working great especially for the Slack notification of PR's, but it'll be great if I can get the same notification for Issues. My suggestion for the notification is like the following:

* [ ] Get notified when I or my team is assigned a issue
* [ ] Get notified when my issue got a comment
* [ ] Get notified when my issue is closed or reopened
* [ ] Get notified when I'm mentioned in a comment

Thanks for creating great app!
Kurt

**Comment by abinoda** [comment]
@Kivol Thanks for submitting this! To gather a little more context, may I confirm that your team uses GitHub issues for project management? Do you use GitHub Projects also? Or something like https://www.zenhub.com?

**Comment by Kivol** [comment]
Yes, we use GH issues for engineering project management, but we don't use GH Projects or zenhub.

**Comment by davidmarcus** [comment]
Just chiming in to say what a game-changer this would be for us.

**Comment by abinoda** [comment]
@davidmarcus Can you let me know the use case? ie. what does your team use issues for and where would notifications be most helpful?

**Comment by abinoda** [comment]
Just logging the fact that @adume also just requested reminders and real time notifications when you "assign" pull requests (vs requesting a review). His use case:

> Assignees are different from authors in our case. The PR author assigns the PR to their team lead, and he/she is the one that selects the reviewers.

**Comment by abinoda** [comment]
Also requested by @ebourmalo

**Comment by DyegoCosta** [comment]
This feature would be really useful for us as well. Meanwhile it's not implemented, I was able to achieve similar behaviour with this https://zapier.com/apps/github/integrations/slack/1596/send-a-github-new-mention-to-slack-as-a-new-message

**Comment by patrickelectric** [comment]
Any update in this matter ?

**Comment by abinoda** [comment]
Sorry, not yet!
