### ISSUE TITLE
Feature request: Review turnaround working hours/days

### ISSUE THREAD

**Issue by davidgoate** [pullreminders/backlog#112]
I am actually a bit unsure myself whether this is a good idea, I can imagine many pros and cons for this - but I feel like some useful discussion could be generated in this thread which might shed some light on the perceived usefulness of the requested feature. One "side effect" we've seen since we started seriously tracking stats (and developers being very aware that stats are being tracked), perhaps due to competitive nature of leaderboards etc, occasionally people are changing behaviour with regards to doing things like assigning PR's into review after 6pm or at a weekend or on a Friday afternoon. The main reason is that if the reviewer doesn't perform the review right away, e.g. until Monday morning after a Friday PM assignment, it makes their "stats look worse". To be clear here, this isn't people being malicious to make someone else look worse by tactically assigning after they go home, it's actually the other way, our team are being more compassionate in behaviour than before and not putting things into review until back in core hours so as **to not impact** the other individual statistically. The obvious downside to this is that if the reviewer didn't mind doing the review, now it would not happen for a day or two over the weekend since no one is aware of the PR other than the author.

I think there could be many arguments made here about working culture, whether it's fair or right for people to create PR's for review outside of "core working hours", what pressure that can put on other people etc which could probably turn into a not very useful debate. But, assuming that this is going on and that this behaviour is voluntary and mostly out of enthusiasm/passion for the company & projects, could there be a type of filter that we could tick/untick to "deduct non working days/times" from the stats on demand so that a review which is passed at 09:30 on a Monday is counted as a 30 min review if it was assigned at 10pm on a Saturday (assuming weekend is not working time and work day set to start at 9am).

I still think  we'd want to be able to easily turn the filter on and off, so that we can actually compare how the numbers are impacted. I can imagine there are some complexities to this internally, but I thought I'd throw this out there for input/thoughts on the feature request.

**Comment by abinoda** [comment]
@davidgoate This is a great write-up, would you mind reposting it here https://github.com/pullreminders/backlog/issues/82 and then I'll respond?

**Comment by davidgoate** [comment]
@abinoda done, would you like me to close this as a duplicate?

**Comment by abinoda** [comment]
Got it
