### ISSUE TITLE
Feature request: way to restrict access to all web-based metrics / leaderboards

### ISSUE THREAD

**Issue by pandacalculus** [pullreminders/backlog#125]
The Slack-based PR reminders are the killer feature for our team. Both the individual reminders, and the channel reminders are very useful.

The web-based metrics and leaderboards are, however, not something I'd want to expose to the general engineering team here - my concern is that they will drive behaviour in perverse ways. 

So I'd like to request that all the web-based reporting can be optionally disabled or (preferably) only available to a particular subset of users (via a Role or Group or whatever).

**Comment by abinoda** [comment]
@pandacalculus This is something we can currently offer manually, but we're working on a turnkey way for users to configure this that should be available soon – which organization are you with?

This was also recently requested by @kppullin

**Comment by pandacalculus** [comment]
@abinoda I'm from canva.com - we have ~250 engineers.

**Comment by abinoda** [comment]
@pandacalculus Thanks. Out of curiosity, are there specific metrics that you'd like to disable or did you want to disable all of them? I'm wondering if it's the "Review turnaround" metric in particular that you might be concerned about, or others as well?

We'll try to have something out for this later this week.  And just to consolidate other recent requests for this here...

@kppullin recently requested:

> For team leads & managers, who should have the appropriate context for properly interpreting the metrics, I can see using them to highlight inefficiencies and areas for improvement.  But for the day to day developer not so much.

@CodyJamesCasey recently wrote in:

> Is there a way to disable certain leaderboards? Specifically in our case, I wouldn't want Pull Reminders to be calculating or showing review turnaround.

**Comment by pandacalculus** [comment]
> Out of curiosity, are there specific metrics that you'd like to disable or did you want to disable all of them? I'm wondering if it's the "Review turnaround" metric in particular that you might be concerned about, or others as well?

I'd probably want to disable all dashboards, and just keep it as a mostly a Slack-based experience for most devs in our group.

**Comment by abinoda** [comment]
@pandacalculus Sounds good. This is in development.

In the meantime, as we've mentioned to @kppullin, if having the metrics available becomes an urgent problem there is a way for us to disable them manually for your account (though it's not ideal for us).

**Comment by kppullin** [comment]
Disabling all dashboards is perfectly fine on my end too.  Perhaps better is only showing it to admins in the linked github organization.

**Comment by abinoda** [comment]
@pandacalculus @kppullin What we're working on is providing a "Settings" page only accessible to users with Owner permissions in your GitHub org. On that settings page, we are going to let you select specific users whom you'd like to allow access to Pull Analytics (dashboards, leaderboards, etc). For users not included in this listm it'll be as if those features do not exist (we're still thinking through the best design for this).

Let me know if that makes sense and if you have any suggestions or other requests.

**Comment by abinoda** [comment]
@pandacalculus Is this blocking you from onboarding more developers from your team? Asking to help us guage the urgency of this.

**Comment by abinoda** [comment]
@pandacalculus @kppullin We've released this in closed beta. I'm going to reach out to both of you over email with instructions.

**Comment by abinoda** [comment]
https://docs.pullpanda.com/products/pull-analytics/user-access
