### ISSUE TITLE
As a user, I would like real time messages in channels when PRs are opened or merged

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#126]
Real-time notifications about pull requests being opened or merged can benefit certain workflows. For example, some teams figure out who should review pull requests as they become available, so having a real-time alert can ensure a fast response versus waiting until the reminder posts.

**UPDATE 2.18 – this feature is available in closed beta. Contact us to have it enabled for your org.**

🚀

**Comment by natashkap** [comment]
Hi there, I would like to have access to this feature. Thanks!

**Comment by abinoda** [comment]
@natashkap What org are you with?

**Comment by abinoda** [comment]
This is now available for everyone.

@natashkap you should see it in your team reminder options.
