### ISSUE TITLE
Feature request: easier Slack acct to GitHub handle mapping

### ISSUE THREAD

**Issue by pandacalculus** [pullreminders/backlog#127]
For us it would be ideal if we could manage the Slack to GitHub mapping using an API or other mechanism that isn't a UI, and doesn't require individual users to create accounts with pullreminders.com. Managing 100s of developers via the current UI is cumbersome (unless I'm missing something?)

**Comment by abinoda** [comment]
@pandacalculus So you can actually just share the link to your account with people and when they sign in the app will link their GitHub and Slack accounts automatically. In your case the URL to share would be `http://pullreminders.com/installs/2562356`

Let me know how that works. We've been meaning to make this clearer in our on-boarding process, we will create a separate issue for that.
