### ISSUE TITLE
As a user, I want to mute notifications from bots and exclude them from metrics

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#130]
Recently requested by @bootstraponline, @at-ishikawa, @mercury2269, @bmalehorn

Pull Reminders automatically includes users with `type='bot'`. However, many teams have custom bots that are normal GitHub user accounts. This issue is for creating a way for teams to blacklist bots that are not actual bots in order to mute notifications from their comments and hide them from metrics/leaderboards.

**Comment by abinoda** [comment]
@bootstraponline @at-ishikawa @bmalehorn This feature has been deployed. There's no link to it yet, but you can access it at `/installs/:id/settings/ignored_users`. Please report back when you've tried it out so we can confirm this ticket can be closed.

@mercury2269 We will release this for on-prem once ^ confirms it's working well in the cloud version.

**Comment by bootstraponline** [comment]
Thanks!

**Comment by bmalehorn** [comment]
Tried it out, and works as expected. Thanks!

**Comment by jamesvphan** [comment]
tried the link above to add ignored_users, but led to 404 page. is this link still valid? im trying to mute notifications from certain bots

**Comment by bmalehorn** [comment]
> tried the link above to add ignored_users, but led to 404 page. is this link still valid? im trying to mute notifications from certain bots

@jamesvphan Works for me - when I sign in I go to https://pullreminders.com/installs/7443629, so I edited that URL to https://pullreminders.com/installs/7443629/settings/ignored_users.

**Comment by jamesvphan** [comment]
ahh thanks @bmalehorn it works for me :)
