### ISSUE TITLE
Round-robin algorithm for Pull Assigner

### ISSUE THREAD

**Issue by nullren** [pullreminders/backlog#132]
is there some logic to it or is it uniformly random from the team? only asking because in the few times I've used it so far, it seems to choose the same person on my team.

**Comment by abinoda** [comment]
@nullren Pull Assigner chooses the assignee who has the least number of reviews requested during the time period (max 30 day window, or less if you "Reset counter"). If you look at the "Reviews assigned" table in the UI it lists everyone's counts.

If you're interested in a different algorithm let me know. I've expected that we would implement some different variations.

**Comment by abinoda** [comment]
@nullren So in your case, what's probably happening is that certain user have probably done more than one less review than the next lowest reviewer. Therefore Pull Assigner would assign that person on the next two pull requests to catch them up.

I should also mention that Pull Assigner counts all review requests, not just the ones issued by Pull Assigner.

**Comment by nullren** [comment]
ah! that makes sense. I think right now because that person is our CTO, they're going to get all the CRs for a period of time until they're "caught up" (especially as other people just naturally get more CRs due to their roles).

> If you're interested in a different algorithm let me know. I've expected that we would implement some different variations.

barring broader conversations about who should be a member of our github team, I would think just a simple uniformly random distribution would suffice.

**Comment by abinoda** [comment]
> barring broader conversations about who should be a member of our github team, I would think just a simple uniformly random distribution would suffice.

@nullren Makes sense. I'm trying to think of what to call the different algorithms. The current one could be called "Equalize distribution", and the one you're requesting could be called "Round-robin" or something.

Also, you requested "Random" but in practice the way this would work is that Pull Assigner would determine assignment by taking turns per team member *without taking into consideration past workload*. That sound good?

**Comment by nullren** [comment]
> Also, you requested "Random" but in practice the way this would work is that Pull Assigner would determine assignment by taking turns per team member _without taking into consideration past workload_. That sound good?

I think that would be fine. my primary use-case is not necessarily to distribute work load, but just ensure that I can get my PRs to different people (knowledge share and get diverse opinions). so ideally, anything that lets me get to as many different people as possible.

**Comment by abinoda** [comment]
@nullren Yep, sounds good.

**Comment by abinoda** [comment]
@nullren Bam, this is done. You'll get an email about it shortly.
