### ISSUE TITLE
As a user, I want DM notifications when I am made an Assignee of a pull request

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#133]
Requested by @adume:

> Assignees are different from authors in our case. The PR author assigns the PR to their team lead, and he/she is the one that selects the reviewers.

**Comment by Minho-Lee** [comment]
@abinoda This feature would be awesome to have!

**Comment by abinoda** [comment]
@adume @Minho-Lee Moving this into development 🚀

**Comment by abinoda** [comment]
@adume @Minho-Lee This is released.
