### ISSUE TITLE
Allow deleting pull assigner configs

### ISSUE THREAD

**Issue by eborden** [pullreminders/backlog#137]
There is no way to delete a pull assigner config. If a proxy team is accidentally given a config then there is no way to utilize it as a proxy. If the config were delete-able then this should be possible.

**Comment by abinoda** [comment]
@eborden Yep, this will be released today! Sorry for the inconvenience. A few other users have brought this up as well

**Comment by abinoda** [comment]
This has been released, also pinging @geoffharcourt

<img width="420" alt="pull_reminders_delete_settings" src="https://user-images.githubusercontent.com/50083/53516084-b0578600-3a88-11e9-89c5-7ede9629b5df.png">
