### ISSUE TITLE
As a user, I would like to be able to ignore a specific pattern of a pull request title from being assigned to reviewers

### ISSUE THREAD

**Issue by maxgutman** [pullreminders/backlog#138]
The use-case for us is we automatically generate PRs that contain multiple already reviewed commits as part of our release workflow. Additionally, we sometimes create PRs that we want to have a peer review before opening it up to others and we usually label those with something like [DO NOT REVIEW]

**Comment by abinoda** [comment]
@maxgutman Is this request for Pull Assigner or reminders?

**Comment by maxgutman** [comment]
Pull Assigner!

**Comment by abinoda** [comment]
@maxgutman Gotcha. Still would like to understand better – is the issue that you're using CODEOWNERS so Pull Assigner automatically gets triggered on all PRs? And so you'd like a way to tell Pull Assigner to not run on certain PRs?

**Comment by maxgutman** [comment]
Yes, exactly, we're using CODEOWNERS to automate every PR

**Comment by abinoda** [comment]
@maxgutman Got it, will get to this soon. Would disabling based on label work or does it have to be title substring?

**Comment by maxgutman** [comment]
Label would work too

**Comment by abinoda** [comment]
@maxgutman Working on this now. Would it be OK if for now we hardcoded a stop-word label on our end, for example a label named `disable-pullassigner`. Down the road we could let you choose your own labels but it'd be simpler for now if we chose some hard-set default like this.

**Comment by maxgutman** [comment]
Sure, that works for us for now.

**Comment by abinoda** [comment]
@maxgutman This is live. Just use the label `pullassigner-ignored` (case insensitive) on any pull request where you do not want Pull Assigner to run. Let me know if you run into any issues!

**Comment by abinoda** [comment]
@maxgutman Please let me know if this resolved your problem!

**Comment by maxgutman** [comment]
Yes it has. Thanks
