### ISSUE TITLE
As a user, I would like to be able to exclude/ingore repos from my org

### ISSUE THREAD

**Issue by ivanstoyanov** [pullreminders/backlog#141]
Our github org has picked up a good number of semi-important repos, who are not quite ready for deletion, and their old PRs and branches skew the pullreminders metrics and create "noise". The current github configuration allows individual repo selection, but I don't want to give up that by default every repo is being watched, i.e. need out-out vs opt-in. 

If github's API doesn't support it, perhaps it can be implemented on the pullreminders side as an "ignore list".

**Comment by abinoda** [comment]
@ivanstoyanov Thanks Ivan. Have you looked into [archiving those repos](https://help.github.com/en/articles/archiving-repositories) – this is a reversible operation on GitHub that keeps the repo around but makes it read-only. Archived repos are excluded from Pull Reminders.

**Comment by ivanstoyanov** [comment]
Great suggestion, thanks. Btw, the repos I archived did get excluded from /prs, but still show up under /merge-time->"Oldest open PRs". Is that by design?

**Comment by abinoda** [comment]
@ivanstoyanov No, PRs from archived repos should not be shown anywhere. Will get that cleaned up in the next couple of days, thanks for reporting it!

**Comment by dimofeev** [comment]
Hey @abinoda,

 Do we have some update here? I still see these PRs...

Best,
 Dimo

**Comment by abinoda** [comment]
@dimofeev Just deployed a fix for this – should be live in a few minutes. Let us know if you're still seeing the issue.
