### ISSUE TITLE
Always assign reviewers

### ISSUE THREAD

**Issue by eborden** [pullreminders/backlog#149]
Pull assigner will not assign a reviewer if all possible slots are already filled.

![image](https://user-images.githubusercontent.com/545655/54772035-8b13ee80-4bd4-11e9-9929-2d4216c2fabf.png)

It would be great to have a setting that always assigns additional reviewers. We use Pull Assigner for two reasons:
1. Removing the need to pick a reviewer.
2. Spreading knowledge.

In the second case it is helpful to always include additional reviewers. Reviewers may be manually selected because they have specific domain knowedge, but in order to satisfy condition _2_, pull assigners should still assign a reviewer.

**Comment by abinoda** [comment]
@eborden Makes sense, we can add an option to toggle this behavior. Will get this added soon.

**Comment by abinoda** [comment]
@eborden There is a new setting for toggling this behavior. Let me know if you have any questions.
