### ISSUE TITLE
`/pullreminders` in Slack provides an http:// URL

### ISSUE THREAD

**Issue by bwalding** [pullreminders/backlog#157]
### Steps

Type `/pullreminders` in Slack

### Actual behaviour

I'm offered an http:// URL rather than https:// URL.

![image](https://user-images.githubusercontent.com/47446/56178986-8c0b3500-6047-11e9-942a-66d7b29f285d.png)

### Expected behaviour

To help prevent MITM / firesheep attacks, the URL should be `https://pullreminders.com/login`

**Comment by abinoda** [comment]
Thanks @bwalding! Will fix and deploy now.

**Comment by bwalding** [comment]
Thanks!

_You know that is a ridiculous turnaround time..._
