### ISSUE TITLE
As a user, I want to be able to blacklist team members in Pull Assigner

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#161]
Requested by @athkalia:

> I would like to have the option to disable some people from being assigned as reviewers to PRs from the Pull Assigner portal even though they are part of the Github Team that is linked to Pull Assigner. This is because:
>
> 1. At the moment I have to be the “Maintainer” of the Github team that does PR reviews so that I can add/remove people from it. At the same time I do not want to be part of the PR review process myself.
> 2. If I remove myself then I will have to rely on our IT support team to add/remove people when they go on holiday, which is not sustainable (takes them 1-2 days to process an IT request).
> 3. I could make other people “Maintainers” as well, but it is my responsibility and I do not really like to depend on other people to do this.

**Comment by Tapchicoma** [comment]
We have the similar issue:
- person in team is on vacation
- person in team is sick
- person in team is working not full week

Would be nice to temporary exclude these people in such cases from the PR assigner.

First 2 cases, possible, can be covered by slack statuses: "vacationing" and "sick"

**Comment by abinoda** [comment]
This feature is planned to be released this week!

Also logging another +1 from @robertmogos:

> Could we temporarily remove someone from the pull of reviewers that is automatically assigned ? Let’s say, in our case, someone goes in vacation for two weeks. We don’t want to get PRs assigned during this time. I know we could solve it by removing the person from the Github team but is not the most optimal solution. Do you have a workaround for this?

**Comment by abinoda** [comment]
@robertmogos @athkalia @Tapchicoma This is shipped 🚀

**Comment by Tapchicoma** [comment]
@abinoda cool :+1: 

I am thinking about the ways of to automate this member exclusion. Is there any api endpoint available for this feature? Or pullreminders app command that user can enter?

**Comment by athkalia** [comment]
I am writing an article about this actually. I automated this by using the slack api and github api. I wrote a job that runs a few times a day and when it spots that someone has a "holiday" or "out sick" emoji on slack it removes them from the pull assigner github team.

**Comment by abinoda** [comment]
@athkalia That's cool!

@Tapchicoma Can you tell me more about how you'd envision the API being used as well as what sort of an app command you were thinking of?

**Comment by Tapchicoma** [comment]
@abinoda at our company we are using 3rd party tool to request holidays/absence. This tool has an api that allows to get info who is absent today. My idea is to have a job that will grab such info each day in the morning from this 3rd party tool and add/exclude people in pull assigner.

Api could look something like this:
- `GET /pullassigner/teams` that would return all teams with memebers
- `UPDATE /pullassinger/{team}/excludes/add` to add team member to excludes
- `UPDATE /pullassigner/{team}/excludes/remove` to remove team member from excludes

App command that could be used by team member:
- `/pullassigner unavailable [some description of time]` - to exclude myself from PR reviews until given time (similar to slack `/dnd` command)
- `/pullassigner available` to remove myself from excludes

From my perspective - api is more important, as it opens doors for automation. People are lazy to do it themself :slightly_smiling_face:

**Comment by abinoda** [comment]
@Tapchicoma Thank you for the write-up. Very helpful. Will think about how to address this.

**Comment by athkalia** [comment]
This is the article FYI for it, in draft status but very close to being published! :) 
https://medium.com/babylon-engineering/bringing-some-order-to-pull-request-reviews-27ac55d181bb

**Comment by abinoda** [comment]
@athkalia ♥️

**Comment by abinoda** [comment]
Related to https://github.com/pullreminders/backlog/issues/158
