### ISSUE TITLE
Wrong user was mentioned in a pull reminder

### ISSUE THREAD

**Issue by ceeser** [pullreminders/backlog#164]
Add two users in slack with usernames `@Thomas Crown` and `@thomas`. Use @thomas to assign a pull request. Sometimes, pull reminder will say that it was `@Thomas Crown` that assigned the pull request.

**Comment by abinoda** [comment]
@ceeser Hi Canute – the linkage between GitHub and Slack accounts is explicit and stored in the database. If you're seeing incorrect linkage you need to relink the accounts from the UI. To do this, go to the "Add users" screen, then click "remove" for the GitHub user(s) who appear to be currently connected to `@thomas` or `@Thomas Crown` in slack. Then, refresh the screen and relink them properly.
