### ISSUE TITLE
PullAssigner works for one repo but not the other

### ISSUE THREAD

**Issue by AliSoftware** [pullreminders/backlog#178]
Hi,

We have multiple repos in our organisation and while in some, PullAssigners is working (I'm not the one who configured it there though), in the other it properly assigns our PullAssigner proxy team to the new PRs (since we configured the `CODEOWNERS` file for that) like the others... but then PullAssigner doesn't assign anyone to those PRs in that problematic repo: it stays as a regular reviewer assigned to the PR and doesn't assign anyone in the proxy team, instead of assigning people and remove itself, like it does for our main repo

What am I missing? Why would it work in one repo and not the other? Am I supposed to configure something to make it work on each repo?

**Comment by abinoda** [comment]
@AliSoftware What is shown in the activity log in the Pull Assigner dashboard?

Otherwise, make sure that both the `Pull Assigner` and `Pull Panda` apps BOTH are enabled for the repo in question. You can double check this by going to your GitHub organization settings -> `Installed GitHub Apps`.

**Comment by AliSoftware** [comment]
@abinoda Thanks for the quick reply.

I just removed and re-added our Pull Assigners proxy team to a PR in that problematic repo, and the activity log shows: 
> Error | repo_inaccessible | Stevenson#20


But the repo is an OpenSource repo, you should be able to see it yourself too: https://github.com/Babylonpartners/Stevenson/pull/20

Maybe it's just that the proxy team is not given access to the repo indeed, despite the repo being OSS. I'll ask IT to double check (I don't have access to my GH org's settings).

PS: One might want to update the Pull Panda docs to mention that step btw?

**Comment by AliSoftware** [comment]
Here's our setup so far:

1. In pullreminders.com, under "Assigners" tab, we have – amongst others – a team added for team "iOS-PullAssigner (iOS-Admin)". So this is supposed to affect people from the `iOS-Admin` GitHub team (which has 27 people in it), using the proxy team `iOS-PullAssigner` (which has 0 people in it, as expected for a proxy team)
2. In a repo of our org where Pull Assigners works, when I go to the repo's Settings under "Collaborators & Teams", we have `iOS-PullAssigner` with `Write` access and `iOS-Admin` with `Admin` access
3. In the repo where it doesn't work, we only had `iOS-PullAssigner` with `Write` access there but no `iOS-Admin`... so I thought that was it... and I added `iOS-Admin` with `Admin` access to that repo too, waited 5 minutes, then removed `iOS-PullAssigner` from our of our PR in that repo and added it again... but alas, I still get `Error - repo_inaccessible`, even if now both `iOS-PullAssigner` and `iOS-Admin` teams have access in that repo's settings

Btw since it's working for 2 other repos in that same GH organization, I'm not sure if the settings at the GH organization level would have something to do with it? (but since I don't have access to settings at this level I'll ask our IT folks to be sure anyway)

**Comment by AliSoftware** [comment]
Ok, this was indeed because of a setting at the GitHub *organization' settings* level, had to have our devops folks add that repo as part of the repos which the app had access too, so it's solved now!

Thanks for the pointers @abinoda !

Do you think it would be worth updating [this doc](https://docs.pullpanda.com/products/assigner) to help people troubleshoot this kind of issues in the future?
