### ISSUE TITLE
Pull Assigner - Newly setup team not showing up as a reviewer selection

### ISSUE THREAD

**Issue by caitlinhawkins** [pullreminders/backlog#179]
I just set up two new teams on pull assigner, but neither are showing up in the list of choices in the "reviewer" box for the team.

**Comment by abinoda** [comment]
@caitlinhawkins Try adding and removing a member for each team – that should force a sync!

**Comment by caitlinhawkins** [comment]
That didn't work :(

**Comment by abinoda** [comment]
@caitlinhawkins Are the teams marked as "secret"? If so that would be the cause.

**Comment by caitlinhawkins** [comment]
No, both teams are marked as "Visible".  I confirmed they have they had the same settings as the existing team that pull assigner is working for

**Comment by abinoda** [comment]
@caitlinhawkins whats your org name? Will run a full sync for you now which should fix it then

**Comment by caitlinhawkins** [comment]
Sense360

**Comment by abinoda** [comment]
@caitlinhawkins Let me know if its not resolved

**Comment by caitlinhawkins** [comment]
:( it's still not there.

**Comment by abinoda** [comment]
@caitlinhawkins Wow, I completely misunderstood the issue!

So the problem you're running into is that the GitHub Teams you created need to actually have read (or maybe write) access to the repos where you're trying to assign them as reviewers on. Otherwise they dont show up as options.

**Comment by abinoda** [comment]
You can manage this under GitHub team settings

**Comment by caitlinhawkins** [comment]
Ah, duh - that makes a lot of sense.  I confirmed all the actual settings, but didn't click through the other pages on the team page.  THANK YOU!!!

**Comment by ShaharCider** [comment]
Kinda weird what you must grant access to a team even if it's a public repo, but thanks for the help @abinoda

**Comment by amlane** [comment]
I'm having this same issue on ucroo-community org with flows-dev-team. I've added the team, added members (days ago) and added them to have "write" access to all the repos and yet the team is not showing up as a reviewer.

**Comment by iskotar** [comment]
> I'm having this same issue on ucroo-community org with flows-dev-team. I've added the team, added members (days ago) and added them to have "write" access to all the repos and yet the team is not showing up as a reviewer.

Have the same issue
