### ISSUE TITLE
As an administrator, I'd like the ability to share access to the Pull Reminders dashboard with guests in my slack organization

### ISSUE THREAD

**Issue by connected-crowshanbin** [pullreminders/backlog#181]
Currently, when guests in a slack organization try opening the Pull Reminders dashboard, they see the message "You’re not authorized to install Pull Reminders for GitHub on <org name>". Guests are pinged by the Pull Reminder slackbot, but cannot go to the dashboard to see analytics, change their ping settings, etc.

I would like a way to give guests of a Slack organization the same access to Pull Reminders as normal members

**Comment by abinoda** [comment]
@connected-crowshanbin This is a known issue – please email support@pullreminders.com with a list of those users' GitHub usernames and we can manually verify them on our end.

**Comment by connected-crowshanbin** [comment]
Hi @abinoda ! I emailed that address with a list of usernames but haven't received a response yet. I just want to make sure I'm not missing a step and that you and your team will get around to it.
