### ISSUE TITLE
Increase threshold range

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#27]
Add the following options to the threshold range... or just make it a text input:

* 30 minutes
* 45 minutes
* 2 days
* 3 days
* 7 days
* 30 days

From @majormoses:

> Now that there are multiple rules it opens a lot of doors but it is limited by the max threshold. The use case is that normally we want to only be pinged on active pull requests every 24 hours so we use labels to filter out when waiting on a user. I'd like to setup a second reminder for further out (say over a month) to remind us about all older pull requests even if they are not active so that we can either ping the user or close it out.

From @stympy:

> The only thing I would add would be additional reminder periods... 1-24 hours is fine, but I'd also like 2 days, 3 days, and 7 days.  Sometimes PRs just aren't that urgent.

From @traviskroberts:

> Is it possible to decrease the reminder time to lower than an hour? We have a guideline at our company to try and approve a PR within an hour. It would be great to set a reminder for 45 minutes.

**Comment by TheFrozenFire** [comment]
:100:

**Comment by abinoda** [comment]
I am merging this into https://github.com/pullreminders/backlog/issues/54

**Comment by abinoda** [comment]
@TheFrozenFire @majormoses @stympy This has been released! You can now set custom "pull request age" settings not limited by the old dropdown options.
