### ISSUE TITLE
As a user, I want real-time DM's for review requests to teams I am on

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#28]

**Comment by abinoda** [comment]
@kwantopia @valkenar Let me know if you guys switch to using team review requests and would benefit from this

**Comment by kwantopia** [comment]
Yes, we are going to setup backend and frontend teams on github to provide convenience to members and increase usage @abinoda

**Comment by kwantopia** [comment]
Btw, instead of real time dm, if all dm pr-reminders can be scheduled at 3PM my time, that would be good too, but can come later.

**Comment by abinoda** [comment]
@kwantopia Yes, users can specify whether they want real-time DMs or scheduled DMs. The scheduled DMs already include team reminders so you should be good there!

**Comment by abinoda** [comment]
merging into https://github.com/pullreminders/backlog/issues/39
