### ISSUE TITLE
Time of Day changes for reminders don't persist

### ISSUE THREAD

**Issue by TheFrozenFire** [pullreminders/backlog#36]
![screenshot from 2018-05-31 08-03-22](https://user-images.githubusercontent.com/948014/40790293-6604a778-64a9-11e8-9dec-cdd7451eaa2d.png)

Changing "Time(s)" creates a notification in the target channel saying it's changed, but the changes don't persist in this edit view.

**Comment by abinoda** [comment]
@TheFrozenFire I'm looking into this now.

**Comment by abinoda** [comment]
@TheFrozenFire I just updated https://pullreminders.com/installs/2294507/notification_rules/393/edit from the UI and was able to remove "8am", so it looks like it is saving. I'm unable to reproduce this elsewhere as well. Could you try again and see if it works now? Or let me know the exact change you're trying to make?

**Comment by TheFrozenFire** [comment]
Maybe it was a caching issue, or a temporary issue. I'll try to reproduce, but I was able to update it myself as well now.

**Comment by abinoda** [comment]
@TheFrozenFire Great, let me know!
