### ISSUE TITLE
As a user, I want label/string filters for personal reminders to work with CODEOWNERS workflow

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#38]

**Comment by abinoda** [comment]
@ashanbrown FYI - thanks for this suggestion

**Comment by ashanbrown** [comment]
@abinoda Just thought I'd check up on this issue. This is the #1 biggest annoyance with pull reminders at my company.  If we could change one thing, this would be it.

**Comment by abinoda** [comment]
@ashanbrown Thanks for nudging on this. Would be happy to try and address it, but I'd like to confirm the issue. Is the issue that with CODEOWNERS, reviewers are assigned immediately when a PR is opened, but that the PR is still in a "WIP" state? Is your request to exclude PRs from personal reminders until the "WIP" label or term is removed? Is your request also to NOT send the real-time direct message notifying the reviewer of the request until the "WIP" label or term is removed?

**Comment by majormoses** [comment]
@abinoda that is a pain point at my employer although with emails.

**Comment by abinoda** [comment]
@majormoses 👍 

@ashanbrown Just wanted to follow-up on my previous comment

**Comment by ashanbrown** [comment]
@abinoda Thanks for the note.  Coworkers of mine who are not in CODEOWNERS still complain about this.  I think the problem is that sometimes PRs get tabled, but reviewers don't want to remove themselves.  Either they're lazy -- hey, they didn't create the PR to begin with -- or they genuinely want to be consulted if the PR is resurrected and merged.  As a general principle, it'd be nice if the flow doesn't allow the PR author to induce work on behalf of the reviewer when that author decides to table that work.  I'm sure the PR author also doesn't quite know the wishes with respect to the reviewers of staying on the PR or not, and might also not want to have to come up with the list again when the work is ready for review.

**Comment by abinoda** [comment]
@ashanbrown Makes sense. Generally, my stance on this has been that "review requests should not be issued until a review is actually being requested", but I understand that's not the reality of how many teams' workflows currentloy work.

Question – what's the bigger annoyance? 

1. That reviewers get the initial DM notification when they are assigned?
2. Recurring reminders which include the PR that they want to be ignored

Because for the case of #2, one solution right now is to simply have users turn off personal reminders and instead just leverage the team reminders which DO support label/string filtering.

Let me know your thoughts.

**Comment by ashanbrown** [comment]
#1 is not a problem. I think the direct pull reminders are the best part.
;) I just wish they included CI results. ;). Almost everyone has opted out
of our team reminders slack channel. I think our team of 20 is too big for
it.

**Comment by abinoda** [comment]
@ashanbrown Ok, I see I see. Just one tip regarding team reminders – generally for a team that size, it'd make sense to split up into more than one Slack channel (ie. #frontend, #api, etc) and then have filtered team reminders post to those channels. 

But I accept this feature suggestion overall. Also...

> I just wish they included CI results

Can you elaborate on this?

**Comment by ashanbrown** [comment]
I think splitting things up would be hard for our team.  We tend to have a lot of overlap in responsibilities.

Regarding CI results, sorry for going off-topic, but basically I'm still waiting for the piece of the puzzle that sends me slack message when my work has (a) been approved and (b) passed CI.  If it fails CI, I'd also like to know as soon as possible.  I haven't had much luck making email work well for this.  Basically, I want my notifications in Slack and I want to be notified as soon as I can take a next piece of action on a PR.  A PR failing CI is immediately actionable.  A PR passing when it has been approved is also immediately actionable.  A PR being rejected during review is immediately actionable.  Even comments on a PR are immediately actionable.  I had been hoping that the Slack-Github collaboration would yield this but I'm still waiting, and now with the Microsoft acquisition it might be wishful thinking to think there will be a lot of progress on this any time soon.  I actually built a system to do all this with phabricator at a previous company, but I was hoping I could find something off the shelf this time.  ;)

**Comment by abinoda** [comment]
@ashanbrown Wanna create a new issue for this? An option for DM alerts for CI results This seems like a great feature to add to Pull Reminders. It'd be nice if you could also include information on what specific CI tools you're using and want alerts about.

**Comment by abinoda** [comment]
Just had a chat w/ @robatwave about this same issue. I've escalated this to the top of the backlog.

**Comment by abinoda** [comment]
@ashanbrown @majormoses @robatwave @cschultztech @sgringwe this is live in production 🙌

**Comment by abinoda** [comment]
There's a link "More settings" under "Your DM Settings". This is deploying now so you'll see it in like 3 minutes.

**Comment by abinoda** [comment]
@plunchete ping – I know you recently requested this as well

**Comment by majormoses** [comment]
@abinoda I am still not seeing it (I see the more settings but nothing that indicates anything about `CODEOWNERS`) and also I think its more important that this is supported at the team level than the individual level.

**Comment by abinoda** [comment]
@majormoses See the screenshot below – this is on the "Your DM Settings" page. What do you mean by "supported at the team level"? String and label filters already exist for team reminders. The goal of this issue was to add those same filtering capabilities to persona/DM reminders.

<img width="796" alt="screen shot 2018-11-08 at 4 46 56 pm" src="https://user-images.githubusercontent.com/50083/48236183-f5d73280-e375-11e8-8ba2-c8a8b9a1468e.png">

**Comment by majormoses** [comment]
Yup I see that but no option underneath related to `CODEOWNERS`

![image](https://user-images.githubusercontent.com/3145127/48236570-b6114a80-e377-11e8-9470-d896f530fa5b.png)

**Comment by majormoses** [comment]
the existing/new filters don't help with the problem outlined. The problem is that people create WIP PRs and do not always (oor in many cases able to) tag appropriately. Ideally if CI is failing there is no sense messaging the team.

**Comment by abinoda** [comment]
@majormoses Based on earlier comments here, the issue I was trying to tackle is that previously there was no way to exclude things like "WIP" from personal reminders at all. In the past, when users brought this up, I replied by saying that they should simply not assign reviews until the pull request was out of a WIP state. However, for teams that use codeowners, review requests are *automatically* generated when the pull request is opened, even if the pull request is in a WIP state. This made it very inconvenient to abide by my suggestion of not assigning or un-assigning reviewers until a review is *actually* needed. Therefore I decided to add filtering capabilities so that WIP, etc. can be excluded from personal reminders. See @ashanbrown's comments earlier as well.

I'm not understanding what you're looking for, but I think it should probably be requested as a separate issue?

**Comment by majormoses** [comment]
> I'm not understanding what you're looking for, but I think it should probably be requested as a separate issue?

Will do

**Comment by abinoda** [comment]
@majormoses We replied at the same time. But I'm not understanding "the existing/new filters don't help with the problem outlined". Before these filters were added, there was no way to exclude WIP pull requests from personal reminders if you were assigned as a reviewer (automatically via CODEOWNERS or manually). Now there is.

**Comment by majormoses** [comment]
@abinoda #95 would help with what I am getting at

**Comment by ashanbrown** [comment]
Thanks @abinoda!

**Comment by plunchete** [comment]
Thanks @abinoda! I think it would make sense to have some org level preferences eg: I don't want to ask everyone on my time to go add wip and whatever else we come up to their preferences.

**Comment by abinoda** [comment]
@plunchete Makes sense. FWIW, WIP prefixes are now ignored by default. That'll be mentioned in the feature announcement going out tomorrow
