### ISSUE TITLE
Delete past reminders from Slack to keep chat history clean

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#40]
Requested by @kiranpanesar:

> Auto-delete the group reminders after X hours. They are good for prompting us to check PRs. But leaves a lot of dust in the group. I don't want people coming to our devs chat and thinking it's mainly for reminders.

This looks possible using https://api.slack.com/methods/chat.delete

**Comment by abinoda** [comment]
@kiranpanesar I think the simplest logic for this would be to just delete the last reminder whenever posting a new one. This way there's only ever one reminder message in the channel.

**Comment by majormoses** [comment]
While I can see it being messy I actually like seeing them in the slack channel as it shows how you are trending (more or less). I'd be open to it being an option though.

**Comment by abinoda** [comment]
Closing for now due to low priority
