### ISSUE TITLE
As a user, I want to snooze direct message reminders

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#46]
From @james-pack:

> I love getting reminded about things I care about, and I had Pull Reminders reminding me every hour. Until I got a review for a 4k LOC PR. I didn't start for several hours -- the author took about a week to write, so waiting a few hours won't matter -- and I couldn't finish the review in an hour. At that point, I didn't want to be reminded of the PR every hour. They became a distraction.

From @cariwest:

> ... possibly also allow a person to "snooze" a reminder (i.e., skip the next reminder)

**Comment by abinoda** [comment]
Curious to hear if you strong upvotes or other suggestions for this @jchavarri, @cobrabr, @lfre, @Incognito...

**Comment by Incognito** [comment]
I think this is needed for one of two cases on my side:
1. Just moving to reminders and having to deal with ancient PRs (weeks or months old) when there's "no time to deal with it right now"
Or
2. Blocked work until another team or business decision is completed.

Both of those are kind of weak arguments to for me to snooze. I should either delegate the first one to my team to resolve. The second case should be re-scoped to avoid "bit-rot".

A 4000loc pr that took a week to write is in general not going to be reviewed correct and is more prone to errors. In previous teams I've had the team rework this (which almost always revealed implementation problems not caught at review time). This can be a hard conversation to have with someone who poured their heart into that PR, so it's better to discuss a plan and why. For example, find the underpinning architecture and have those components made into individual PRs. Or slice it into "business releases" where you only impact one function of the business at a time. It's not easy to split up a 4k PR, but anything above 250loc is likely to not be correct.

I scanned all PRs of 300 of the most popular repos on GitHub and found anything with more than 100 lines of code per commit and 10 commits is beyond the upper threshold where comments happen. 250loc is the "sweet spot" between productive daily PRs and accurate code reviews.
(Obviously this excludes lock files).

**Comment by cobrabr** [comment]
I haven't found the need for snoozing reminders _yet_, but I can see how a large PR would be something I would like to snooze from time to time. I've had to deal with PRs like the one @james-pack mentioned, and I've definitely postponed starting the review on those to the next day. :wink:

**Comment by lfre** [comment]
I think snoozing might create a behavior that could easily become the norm where every PR is snoozed and then you forget about it.

To me, large PRs should be the exception and not the rule. Additionally, the definition of a "large PR" is subjective (lines of code, complexity, test case scenarios, etc). Each application/team could easily have a different definition of what it is considered "large".

I think this could be solved through a label, and allow the app to create an override schedule for that specific label or keyword. A label would also give you the ability to filter "large PRs" in your repo and have a better insight into why these couldn't have been split up in the first place.

**Comment by jchavarri** [comment]
I haven't found the need for it either (at least, yet). In general, code reviews take priority over almost everything else, so the longest that a PR goes unreviewed is one day in my case. We also make a lot of efforts to keep the PRs small, like others in this thread have mentioned. 

> and I had Pull Reminders reminding me every hour

Maybe setting the reminders to happen less often would help in that case? Once per hour seems too frequent imo, especially if the user is finding them distracting (considering there's also a notification when a new review is requested).

**Comment by majormoses** [comment]
I have not needed it in this form...what I have been doing is having my DMs sent 3 times a day so that I see what it looks like in the morning, what it looks like after work, and what it looks like in the evening. While thats more notifications it has worked pretty well for me. If something is not ready for review the maintainer can add a label to remove it from reminding them.

**Comment by abinoda** [comment]
Closing this due to low priority
