### ISSUE TITLE
As a user, I would like to receive DM's when I am @mentioned in a PR comment

### ISSUE THREAD

**Issue by lishenzhi** [pullreminders/backlog#47]

**Comment by abinoda** [comment]
@lishenzhi Thanks for submitting this!

**Comment by abinoda** [comment]
@lishenzhi My only concern with this is that it might be quite noisy. e.g., if you get several @mentions on the same PR in the span of a minute. I'm wondering if it'd be good to throttle the Slack notifications so you don't get a bunch at the same time.

Is my concern valid? What do you think?

**Comment by lishenzhi** [comment]
@abinoda absolutely. I agree with you that some throttle will be better than instant message. I like what you have in the direct message setting now, to get instant message and/or set the reminder schedule. Can we have the same settings for mention also?

**Comment by abinoda** [comment]
I'm merging this into https://github.com/pullreminders/backlog/issues/59#issuecomment-410888576
