### ISSUE TITLE
[GitHub Issue] GitHub's UI for re-requesting reviews is not intuitive and mostly not known

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#48]
# Background

For teams using [Pull Reminders](https://github.com/marketplace/pull-reminders/) with [GitHub review requests](https://blog.github.com/2016-12-07-introducing-review-requests/), reminders include pull requests that are `Waiting for review` and `Waiting for author` (when this feature is enabled). Pull Reminders considers a PR to be `Waiting for review` if it has review requests, or `Waiting for author` if it has received reviews but does not have any pending review requests.

# Getting stuck on "waiting for author"

A common problem that teams contact me about is that their pull requests show as `Waiting for author` even after an author has responded to submitted reviews or comments. This problem occurs when the author does not create new review requests after addressing the initial round of review — review requests are deleted once a comment or review is submitted by reviewers, so to change pull requests back to `Waiting for review`;,authors must re-assign reviewers after responding to reviews and comments.

The images below highlight what this looks like. After I've submitted a review for requested changes, I show up under "Reviewers" with a red x beside my name. If I click the gear icon, I see that I am no longer a requested reviewer and can be assigned again.

<img width="740" alt="artboard 2" src="https://user-images.githubusercontent.com/50083/41500436-b4b772b0-7156-11e8-934b-6c7bed22d7f8.png">

# GitHub UX issue

I have found that many GitHub users are unaware of the behavior I've described above, and that GitHub allows you to request reviews multiples times from the same reviewer . This leads to sub-optimal workflows where users create review requests for their initial round of review, but then come up with ad-hoc ways of dealing with with requesting subsequent reviews/.

# Suggestion for GitHub

I believe that code review processes on GitHub would be better by default if the UI provided “Request another review” calls-to-action in context. This would lead to users naturally requesting multiple rounds of reviews instead of users resorting to ad-hoc workflows.

I've illustrated a couple of examples of what I mean below. For example, after a review request is deleted, it would be great to display a "Request another review" link beside the reviewer's name in the "Reviewers" list. Similarly, when a review or comment is submitted, it would be great to display a "Request another review from <reviewer name>" call to action nearby.

<img width="389" alt="screen shot 2018-06-16 at 12 17 20 pm" src="https://user-images.githubusercontent.com/50083/41500853-45f21c3c-715f-11e8-8f66-efb32d2f0eec.png">

<img width="783" alt="screen shot 2018-06-16 at 12 51 30 pm" src="https://user-images.githubusercontent.com/50083/41501145-15d7ffd0-7164-11e8-9159-9015953b27ad.png">

**Comment by abinoda** [comment]
@Chris-td This is the write-up for the issue I I emailed you about. Would love to hear if you have any additional thoughts on it.

**Comment by abinoda** [comment]
@jchavarri This was an issue that @callmevlad brought up to me early on. Are you still having problems with it? If not, did you change your workflow or workaround it some other way?

**Comment by jchavarri** [comment]
I haven't personally run into this issue, but I see how it can be confusing. If I understand correctly, the only state where a review is in "Waiting" state is when there's the yellow/orange dot next in the review panel, right?

**Comment by abinoda** [comment]
> If I understand correctly, the only state where a review is in "Waiting" state is when there's the yellow/orange dot in the review panel, right?

That's correct. When there's an incomplete review request it is shown as an orange dot.

**Comment by abinoda** [comment]
@lukehefson Hi Luke. Wanted to ping you from this issue since I saw you're heading up Papercut and I saw you getting involved @ https://github.com/sindresorhus/refined-github/issues/1469#issuecomment-411465483.

I'm the creator of [Pull Reminders](https://github.com/marketplace/pull-reminders), and as part of my work, have gotten to get an up close look at the GitHub code review workflows of hundreds of different organizations.

A recurring issue is that the workflow for requesting a 2nd/3rd/etc review is not clear. The consequence of this is that users typically use GitHub review requests initially, but after the initial review they resort to using comments (i.e. "hey can I get another review?) which breaks things out of the review request workflow and all the benefits of it.

Here's an email exchange with a user from just today as an example:

<img width="887" alt="screen shot 2018-08-09 at 2 41 41 pm" src="https://user-images.githubusercontent.com/50083/43927455-74d34cbc-9be2-11e8-9c38-73e20256ffe0.png">

My suggestion to resolve this is for GitHub to add a "Request another review" link under "Reviewers" when the reviewer has previously left a comment or requested changes. It would also be nice to add "Request another review" calls to action within the PR thread itself. I'm sure there are other solutions as well, but the basic idea is to make it obvious to users that they can and should create a new review request.

**Comment by lukehefson** [comment]
Hey @abinoda. Ah yes, this is very good feedback, and I think we're heard similar comments from users in the past.

Unfortunately, I think that it's probably out of the realms of our Papercuts initiative – due to being a little more 'part of a full workflow' – but I'll make sure to surface it with the relevant Product team for consideration!

**Comment by abinoda** [comment]
@lukehefson Sounds good, thanks!

**Comment by Flamefork** [comment]
Any chance for this to move forward?

**Comment by lukehefson** [comment]
> Any chance for this to move forward?

Hey @Flamefork! We're currently working on solutions for it right now, but don't have a set release date. Please keep your eye on https://github.blog/changelog/ (and this issue) for updates!

**Comment by abinoda** [comment]
@Flamefork @mikeocool I'm closing this issue because GitHub released a new feature to address this:
https://github.blog/changelog/2019-02-21-re-request-review-on-a-pull-request/

Thanks @lukehefson! I'll be communicating this with many more users over email.
