### ISSUE TITLE
As a user, I would like Pull Reminder to support SLA & reporting on different groups

### ISSUE THREAD

**Issue by lishenzhi** [pullreminders/backlog#49]
would like to be able to config the team members into different groups like developers, QA & PO. And for each group, could set different SLA and report based on that.

**Comment by abinoda** [comment]
@lishenzhi Thanks for submitting this. I think this should be merged into https://github.com/pullreminders/backlog/issues/35. Is it ok if I do that?

**Comment by abinoda** [comment]
Merging into https://github.com/pullreminders/backlog/issues/35
