### ISSUE TITLE
As a user, I would like to receive a DM when someone leaves comments on my PR

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#59]
From @andreasklinger:

> People struggle to realize there have gotten replies to their comments. They don't check their emails or have even unsubscribed from those GitHub notifications so it would be awesome if Pull Reminders could ping you (optionally) if there is a comment to a PR of yours OR a reply to one of your comments (in any PR)

**Comment by nbasu02** [comment]
As a user with a lot of extra github emails, this would be a huge help.  My coworkers leave me comments that I sometimes don't see for days.

**Comment by abinoda** [comment]
@nbasu02 Yep, this is rising in priority. Also logging a note from @andreasklinger:

> people struggle to realize there was a reply to some comment. they don't check their emails or even unsubscribed from those notifications it would be awesome if pull-reminders pings you (optionally) if there is a comment to a PR of yours OR a reply to one of your comments (in any PR)

Also, noting the overlap with https://github.com/pullreminders/backlog/issues/47

**Comment by abinoda** [comment]
@andreasklinger @lishenzhi @nbasu02 I would love your feedback on my thoughts below.

I've been mapping out what the best way to solve this is. A simple, naive approach would be to send Slack DMs for every single comment on your PRs or that you are @mentioned on. My concern with this is the noisiness – for example, its common for reviewers to leave several disparate comments while going through a PR, and this would often bombard you in Slack with DMs. Even though this feature would be optional, I don't like the idea of disrupting people with so many DMs.

To address this, I've been kicking around the idea of having some sort of arbitrary "throttling" – for example, I could have logic that only sends you a DM if you haven't already received a previous DM for the same PR within  some timespan (ie. 5 minutes). The problem with this is that I think it would be confusing to arbitrarily skip notifications and could lead to things getting accidentally missed. For example, if two comments come in 2 minutes apart, should we send one DM during the first comment, and then skip the 2nd one? Or wait a certain period of time before sending any?

Because of this, the direction I'm starting to lean toward is to not introduce any real-time comment DMs at all. Instead, I could build a feature that reminds you (in the existing scheduled reminders) of comments on open PRs (either comments on YOUR PRs or comments in other PRs that mention or reply to you) that you haven't responded to or taken some UI action since. I think this would provide a nice balance in terms of making sure comments aren't forgotten, but also not creating a disturbance of Slack DMs. The challenge with this approach is figuring out a good way to treat a comment as "unresponded"...

What do you think?

**Comment by abinoda** [comment]
@jchavarri @Incognito @lfre @cobrabr I'd love your thoughts on the value and approach to this feature I am exploring!

**Comment by nbasu02** [comment]
I have no opinion on reminders for comments that I haven't responded to - I probably wouldn't use that feature.

One guy on my team will throw 10 comments at you in a matter of a few minutes.  I think optional throttling with the ability to adjust would be helpful (not everyone has that guy on their team).  It can default to five or however many minutes with a link to how to update the throttling?  I personally wouldn't care to throttle messages if I'm @-mentioned, but I'd get someone might want to avoid being trolled so it would still be helpful.

**Comment by abinoda** [comment]
@nbasu02 

> I have no opinion on reminders for comments that I haven't responded to - I probably wouldn't use that feature.

👍  Gotcha, thanks for this.

> One guy on my team will throw 10 comments at you in a matter of a few minutes. I think optional throttling with the ability to adjust would be helpful (not everyone has that guy on their team). It can default to five or however many minutes with a link to how to update the throttling? I personally wouldn't care to throttle messages if I'm @-mentioned, but I'd get someone might want to avoid being trolled so it would still be helpful.

Customizable throttling options is an interesting idea... if I take that and run with it, here's the complete solution I'm thinking of:

- Fire a DM for every comment that is either (a) on your PR, (b) @mentions you, or (c) a reply to one of your previous comments
- Allow for a customizable throttle option to delay and group comment notifications. For example, if you select "5 minutes", you'd never receive more than one comment DM per PR within a 5 minute timespan.
- Recommend to users that they submit code review comments in one submission vs separate individual comments. This avoids DM spam.

**Comment by nbasu02** [comment]
I think the third point would be a nice touch too.  Though it may not be a problem if the throttling is on by default, would it?

**Comment by abinoda** [comment]
@nbasu02 I think throttling would cover most cases. I'm just trying to avoid throttling as much as possible since I think it introduces the potential for good notifications to not get sent.

**Comment by atopiler** [comment]
Feels like github's slack integration handles this pretty well, by combining all review comments into a single update.  Comment replies are a different story, but either way, you might want to feel out how the github's main slack integration works and find ways to improve on that by directing certain updates to only certain people (right now, all you can do is have all updates go to a certain slack channel, but there's no way to personalize that for each user based on which comments or replies might be relevant to them).

**Comment by abinoda** [comment]
@atopiler Thanks! Yeah, batching review comments (when they are submitted together) shouldn't be an issue. It's the replies that I'm scratching my head about a bit more. Either way, I think most of my concerns about this feature have been addressed so I should be moving it into development soon.

**Comment by abinoda** [comment]
I've edited this issue title so it is scoped to only DMs when your PR receives comments. I've created a separate issue for DMs when you are mentioned on comments or someone replies to your comment: https://github.com/pullreminders/backlog/issues/65

**Comment by abinoda** [comment]
@atopiler @nbasu02 @andreasklinger I've released the ability to receive DMs for comments on your PRs – you can opt into it under "My DM Settings". I'll do a broad announcement later this week but would love your feedback on it in the meantime.

Couple notes:
1. I did not include preview text in DMs for inline code comments because there's the potential for there to be a lot of disparate comments and I wasn't sure how helpful preview messages would be outside the context of the PR diff. Let me know if this feels missing, though.
2. I only built DMs for comments you receive on your PRs. For @mentions and replies on other PRs, I've created a separate issue https://github.com/pullreminders/backlog/issues/65
