### ISSUE TITLE
Make it more clear what organization you're in

### ISSUE THREAD

**Issue by tas50** [pullreminders/backlog#62]
I manage several organizations and it's difficult to see what org you're currently logged in as. It would be helpful to show what org you were in so I could switch between them easier.

-Tim

**Comment by abinoda** [comment]
@tas50 Thanks Tim. Have you seen that clicking the icon in the top left opens an account switcher? Let me know if this was unclear and I can think of ways to make it more obvious.

Also maybe I should display your current org icon instead of the Pull Reminders logo?

**Comment by tas50** [comment]
I clicked around and eventually figured out you could use that to switch orgs. It still doesn't show you what org you're currently logged in as though.

**Comment by abinoda** [comment]
@tas50 Cool, I agree that its confusing to not easily know which org you're in. I'll work on an improvement for this.

**Comment by majormoses** [comment]
Yup I had similar usability issues and look forward to seeing this improved.

**Comment by abinoda** [comment]
From @morganwalker:

> Hovering over that icon show https://pullreminders.com, which makes me think it's just going to link back to your landing page. It's not clear that clicking the icon gives you the ability to add or switch orgs.

**Comment by abinoda** [comment]
@tas50 @majormoses @morganwalker This is live 🚀 . This was definitely long overdue – hope it's much easier to navigate between orgs now!

**Comment by majormoses** [comment]
Thank you!

![image](https://user-images.githubusercontent.com/3145127/51801387-c657f980-21f1-11e9-94d4-c2f2bc48af6c.png)
