### ISSUE TITLE
feature request: ignore bots

### ISSUE THREAD

**Issue by Br3nda** [pullreminders/backlog#63]
We use a few GitHub bots for dependency updates etc.
I'd like to remove these from the leaderboards.
Github API does mark bots as bots, so you can probably detect these accounts.

**Comment by abinoda** [comment]
@Br3nda Are these custom built bots? Or external services? I do have a list of bot users I globally exclude so happy to add to that.

>  Github API does mark bots as bots, so you can probably detect these accounts.

I'm not seeing this, if you could point this out to me I'd appreciate it!

**Comment by Br3nda** [comment]
The bots i've used include
https://github.com/dependabot
https://github.com/renovate-bot
https://github.com/backstroke-bot


I think the method in GraphQL is here 
https://developer.github.com/v4/reference/object/bot/

Backstroke bot has made our leader board, but at least it's not winning.
![image](https://user-images.githubusercontent.com/12266/43934836-475e7c16-9ca5-11e8-82d7-02114c25fd77.png)

**Comment by Br3nda** [comment]
Side note: @hh is winning our leaderboard. he's a lovely outside contributor who sent us one PR.

**Comment by abinoda** [comment]
@Br3nda I've added backstroke-bot to the blacklist. I already have dependabot, reonvatebot, etc on that list. Let me know if any others come up. I'm looking into the API to see if I can automatically identify bots in the future.
