### ISSUE TITLE
As a user, I want to be able to include unassigned pull requests in team reminders (when the "Require review request" option is checked")

### ISSUE THREAD

**Issue by osterman** [pullreminders/backlog#64]
## what
* Receive a notification when a Pull Request is not assigned to anyone

## why
* We have 200+ open source repos
* We frequently miss PRs by contributors who are not able to assign PRs to anyone

## references
* https://github.com/cloudposse

**Comment by abinoda** [comment]
@osterman Thanks for submitting this! Just want to clarify – are you interested in having an option to include PRs with no reviewers included in team reminders? Just want to confirm you're not talking about personal DMs or reminders.

**Comment by osterman** [comment]
> are you interested in having an option to include PRs with no reviewers included in team reminders

Yea, I think that would be a good way to surface them. 

Basically, it would report:

- Waiting for review (existing)
- Waiting for author (existing)
- Unassigned (new)

**Comment by abinoda** [comment]
@osterman Makes sense. Tagging this and moving to the backlog.

**Comment by abinoda** [comment]
@osterman This is released in closed beta and enabled for your org. Can you let me know how it works one you've had a chance to try it?

cc: @taylorturner

**Comment by osterman** [comment]
Wooohooo @abinoda ! Will give this a go

**Comment by abinoda** [comment]
@osterman We noticed that there was a bug in this that basically made it non-functional. We pushed a hotfix for it so it should work now if you noticed that it wasn't before.

**Comment by Joeper214** [comment]
@abinoda  Hi I would like to know if this is already supported in pullreminders.com dashboard? If so, I would like to know how to use it. Thanks

**Comment by Joeper214** [comment]
We also want to integreate this in our open source repo. 

https://github.com/blue-oil/blueoil
