### ISSUE TITLE
As a user, I want set default DM settings for other users before onboarding them

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#67]
Requested by @plunchete

**Comment by majormoses** [comment]
To further clarify does that mean setting team defaults where anyone who joins the team defaults to those settings or is this specific to individual users?

**Comment by abinoda** [comment]
@majormoses This is for "My DM Settings". When onboarding other users, you'd be able to set the default settings for the users you are inviting

**Comment by majormoses** [comment]
Rather than doing that every time would it make sense to instead have it be something generic defaults for the team? I guess it depends on how your org works but in my use cases the team level defaults for "My DM Settings" would be nicer but it makes sense both ways.

**Comment by abinoda** [comment]
@majormoses Yeah, what you suggested is a possible implementation. I haven't decided what the exact implementation would look like yet :)

**Comment by plunchete** [comment]
When I first suggested this to @abinoda my idea was to kick out a preferences flow when sending out the invite. While having a default one isn't bad that wouldn't work for my team since everyone has slightly different schedules / time when they want to be heads down

**Comment by abinoda** [comment]
Closing for now due to low priority
