### ISSUE TITLE
Don't send review request DM's until PR checks have passed

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#68]

**Comment by majormoses** [comment]
Hmm I am torn on this, on the one hand it means that you are not being spammed with requests that are being currently acted on but on the flip side it means that if a user needs help with getting tests to pass it is very easy to slip through the cracks. I think this would be a good idea as an opt-in and have some verbiage to that point. I think if I were to use this I would want a rule with it enabled and one with it disabled using different time thresholds.

**Comment by abinoda** [comment]
Dupe of https://github.com/pullreminders/backlog/issues/95
