### ISSUE TITLE
Pull Request Dashboard

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#7]
Requested by @jadametz:

> The ability to look at a page and ask "which reviews need my attention?" The page might even show all PR's but highlight the ones that aren't ignored by label or title patterns.

**Comment by majormoses** [comment]
While I think there is a lot of good here I worry that in order for it to be useful we would need to expose the full github search so that you can filter by labels and such. That being said I would love to see this happen as this is a big pain point for OSS maintainers across multiple orgs.

**Comment by abinoda** [comment]
Closing for now due to low priority
