### ISSUE TITLE
As a PR author, I would like to receive a DM when my pull request gets merged by someone else

### ISSUE THREAD

**Issue by petegivens** [pullreminders/backlog#70]
I work on a team where only leads have access to merge PRs into master. It would be great if I could receive a DM when my pull request has been merged.

**Comment by abinoda** [comment]
@petegivens Thanks for submitting!

**Comment by majormoses** [comment]
At the company I work at each repo has one or more teams that can merge code into protected branches while anyone in the org can submit a pull request. I can see it being useful but I wonder if this creates more spam as you get an email from github already when a pull request is merged. I am not opposed to implementing this I just think we should probably default to off and let users opt in as we can't know what they are getting from email.

**Comment by abinoda** [comment]
@majormoses Thanks for the feedback!

> I wonder if this creates more spam as you get an email from github already when a pull request is merged

I'm seeing a strong trend toward folks wanting to move away from email notifications entirely, in favor of having all notifications come through Slack. Based on this, I think this feature request makes sense for the exact reason that it would replace the need for someone having to rely on the email notifications.

**Comment by abinoda** [comment]
@petegivens @brad-decker @carlangueitor @johnnypez @bobheadxi

We are working on allowing optional real time notifications in channels when PRs are opened or merged – see https://github.com/pullreminders/backlog/issues/126. That should address the use case described here so I'm going to close this issue. If anyone disagrees please reply here!

**Comment by abinoda** [comment]
@petegivens @brad-decker @Carlangueitor @johnnypez @bobheadxi @adume 

This is live. There's a new option under "My DM Settings" for getting notified when someone else merges your pull request.
