### ISSUE TITLE
As an administrator I would like to set business hours so that time based metrics account for nights and weekends

### ISSUE THREAD

**Issue by brad-decker** [pullreminders/backlog#71]
I was trying to figure out how we had some reviews that took multiple days waiting for review and realized that those were ones that were requested for review on friday and didn't receive a review until monday. Anyway this can be controlled?

**Comment by abinoda** [comment]
@brad-decker Definitely! I'm going to merge this into the existing issue that covers this: https://github.com/pullreminders/backlog/issues/35

**Comment by brad-decker** [comment]
Thanks @abinoda :)
