### ISSUE TITLE
As a user, I would like to receive a DM when someone replies to a comment I posted

### ISSUE THREAD

**Issue by abinoda** [pullreminders/backlog#74]
From @stephenh:

> I love pullreminders and use it for all "things I should know about in PRs". Currently it works great for PRs I open, and PRs that people assign to me, but what I'm missing is "a PR I did not open, but have commented in, send me any replies to that conversation".

From @andreasklinger:

> It would be nice if Pull Reminders could ping you (optionally) if there is a comment to a PR of yours OR a reply to one of your comments in someone elses PR

**Comment by jacklynrose** [comment]
👍

**Comment by abinoda** [comment]
@watsonhamblin @stephenh @ccpost @galenscook This was just shipped! The notification will say `<user> replied to you in <thread>`. Note that it may take a little bit for Pull Reminders to backfill old comments, so you might not immediately start getting notifications for threads where you haven't commented since this was deployed.

**Comment by ccpost** [comment]
I got some of these notifs today and it was really helpful! 👍
