### ISSUE TITLE
As a user, I would like to a Dashboard for review quality (ie. # of comments)

### ISSUE THREAD

**Issue by tictacteox** [pullreminders/backlog#78]
I like that the metrics, trends, and leaderboards can give me a good pulse on my team's PR reviewing efficiency. I would love to also get a pulse on PR review quality. For example, I think that if there were a leaderboard that counted number of comments left on PRs that could be a really good signal.

**Comment by abinoda** [comment]
Thanks @thisisthais. I like this idea, but I'm not sure if it makes sense to be displayed as a "leaderboard" versus a separate section for just viewing this metric? What do you think? I guess what I'm saying is that the "leaderboard" tends to imply that more is better, and I'm not sure more comments is necessarily a metric that we should be striving for.

**Comment by abinoda** [comment]
Adding some similar suggestions received over email to this thread:

From @K11MAR:

> Are we able to view the amount the comments associated to PRs from a statistics perspective? Trends/results etc"

From @austinwiltshire:

> How hard would it be to track metrics like the following:
>
> * Total number of comments, for some period, for some engineer
> * Total number of peer requests, for some period, that some engineer took part in (not as an author)
> * A ratio of the above - basically, best commenter, for some period, by average comments per PR they took part in.

**Comment by austinwiltshire** [comment]
Leaderboard might also make things too competitive. People might just start commenting to game the system.

**Comment by abinoda** [comment]
@austinwiltshire Yeah, I think the word "leaderboard" is a bit loaded. I'd like to move more metrics into a more neutral presentation thats not focused on ranking people.

**Comment by wildcard** [comment]
The following would be really helpful:
- [ ] Counting comments on PR
- [ ] Counting resolved conversations on PR
- [ ] Number of owned comments on PR (I want to praise devs for self reviewing)
- [ ] Number of given comments (feedback by other teammates)
- [ ] PR has been editted after an approval
- [ ] PR has been editted after an disapproval - new code to review

**Comment by abinoda** [comment]
@thisisthais @davidgoate @wildcard @austinwiltshire @K11MAR @stephenh @designjockey @alexmitc

We added comment count and a comments-to-pr-reviewed ratio to the "Reviews" leaderboard. This is available for your teams in closed beta. 

Please let us know your feedback. We'd especially like to hear how it is received by your teams, and what other reporting capabilities around comments would provide additional value.

#### Release notes

* For any Pull Request, GitHub provides three kinds of comment views: comments on the Pull Request as a whole, comments on a specific line within the Pull Request, and comments on a specific commit within the Pull Request. *Currently we are only counting "comments on a specific line within the Pull Request"*.
* We just added review comments to our historical sync scripts so data going back further than 45d may not be 100% accurate.

**Comment by abinoda** [comment]
This feature is now available to everyone.
