### ISSUE TITLE
As a user, I would like to be able to scope metrics by Github team

### ISSUE THREAD

**Issue by zan-rosenthal** [pullreminders/backlog#79]
Our overall dev team is split into 2-3 smaller teams at any given time, contributing mainly to the same codebase. Currently, I see metrics for all collaborators in our organization in Github. I would like to be able to choose to see metrics relating only to my team. In terms of the UI, I'd be happy with either scoping it by an already existing Github team or selecting which individual users I want to include within Pull Reminders.

**Comment by abinoda** [comment]
@zan-rosenthal Thanks Zan! This'll be done very soon.

**Comment by abinoda** [comment]
@zan-rosenthal @philboyd A team filter was added to the leaderboard. Currently working on adding it also to the "Metrics" section

**Comment by zan-rosenthal** [comment]
@abinoda Awesome. Thanks.

**Comment by abinoda** [comment]
@zan-rosenthal @philboyd I'm marking this card as done per the release that just went out an hour ago.
