### ISSUE TITLE
As a user, I'd like a notification when CI results/Checks are ready

### ISSUE THREAD

**Issue by ashanbrown** [pullreminders/backlog#81]
When CI results come in, positive or negative, there are actions I can take immediately.  For CI successes, I want to know the status of a PR review, so I can know to merge my PR.  For CI failures, I want to know what failed immediately so I can make changes and push up a fix.

Fwiw, while we use CircleCI, we don't use CircleCI Checks.  We also use Code Climate, which is another result that could be immediately actionable.

**Comment by abinoda** [comment]
👍 Adding to backlog

**Comment by abinoda** [comment]
@ashanbrown My bad, realized this is a dupe of https://github.com/pullreminders/backlog/issues/69 so I'm merging this one into that one. This is coming soon!

**Comment by sleepylemur** [comment]
@abinoda looks like failure case got handled in #69 but also being notified on ci success would be sweet.
