### ISSUE TITLE
If a repo is moved to another org it still shoes on the dashboard

### ISSUE THREAD

**Issue by tas50** [pullreminders/backlog#87]
The PR dashboard is a cool feature. I've been digging in to see what old cruft we have around. We've been in the process of moving some of our EOL projects into a "boneyard" org. I'm noticing that the repos I moved late last week still show up on the dashboard. Any way to get this to refresh so the old junk gets taken off the list.

**Comment by abinoda** [comment]
@tas50 I'll look into this.

**Comment by abinoda** [comment]
@tas50 Deploying a fix for this now – check back in 5 mins but marking this as resolved. Separately, would love suggestions on ways to make the PR Dashboard more useful (ie. quick filters / sorting).
