### ISSUE TITLE
Large names in PR dashboard cause repos selection to draw off screen

### ISSUE THREAD

**Issue by tas50** [pullreminders/backlog#88]
We have some very large repo names and the repos selection list draws from right to left, which causes it to draw off the left hand side of the screen.

![image](https://user-images.githubusercontent.com/1015200/48025663-eac39e80-e0f8-11e8-91e6-b6ff2668a06d.png)

**Comment by abinoda** [comment]
@tas50 Sorry this took so long to fix, but it should be good now!
