### ISSUE TITLE
Only ping to a single slack with product announcements

### ISSUE THREAD

**Issue by tas50** [pullreminders/backlog#90]
I'm on 3 different github orgs with Pull Reminders and I get 3 different direct messages when new features are released. Any chance we could consolidate these to a single Slack.

**Comment by abinoda** [comment]
@tas50 Since https://github.com/pullreminders/backlog/issues/91 will be added, you can just opt-out of feature announcements for all but one org. I don't think this is a common enough case to warrant me adding "automatically avoid sending more than once" logic. Re-open if you disagree.
