### ISSUE TITLE
Enable opting-out of DMs about new product features

### ISSUE THREAD

**Issue by tas50** [pullreminders/backlog#91]
Some of our users have complained about the product feature DMs. Could we get the ability to turn this off?

**Comment by abinoda** [comment]
@tas50 Thanks for creating this. Agree 💯 and I plan on adding this with or prior to the next feature announcement. Only thing is I think this opt-out feature will need to be announced via DM...

**Comment by abinoda** [comment]
@tas50 This is done – there is a new option added under "Your DM Settings". I'll also mention this in the next feature announcement
